insert into customers (name, surname, age, phone_number) values ('Алексей', 'Иванов', 18, '8999999999');
insert into customers (name, surname, age, phone_number) values ('Ирина', 'Петрова', 40, '8777777777');
insert into customers (name, surname, age, phone_number) values ('Пётр', 'Иванов', null, '');
insert into customers (name, surname, age, phone_number) values ('Оксана', 'Сидорова', 25, '');
insert into customers (name, surname, age, phone_number) values ('Иван', 'Иванов', 56, '85555555555');
insert into customers (name, surname, age, phone_number) values ('АЛЕКСЕЙ', 'Павлов', 21, '81111111111');
insert into customers (name, surname, age, phone_number) values ('Иван', 'Иванов', 37, '+375293333333');
insert into customers (name, surname, age, phone_number) values ('Валентина', 'Сидорова', 48, '+71111122222');
insert into customers (name, surname, age, phone_number) values ('Мария', 'Сергеева', 19, '88888888888');
insert into customers (name, surname, age, phone_number) values ('алексей', 'Николаев', 63, '8223215564');

insert into orders (customer_id, product_name, amount) values (6, 'Ноутбук', 47000);
insert into orders (customer_id, product_name, amount) values (2, 'Смартфон', 15000);
insert into orders (customer_id, product_name, amount) values (8, 'Клавиатура', 1500);
insert into orders (customer_id, product_name, amount) values (3, 'Системный блок', 52000);
insert into orders (customer_id, product_name, amount) values (6, 'Принтер', 17000);
insert into orders (customer_id, product_name, amount) values (10, 'Монитор', 9000);
insert into orders (customer_id, product_name, amount) values (9, 'Смартфон', 45000);
insert into orders (customer_id, product_name, amount) values (5, 'Ноутбук', 31000);
insert into orders (customer_id, product_name, amount) values (7, 'Ноутбук', 74000);
insert into orders (customer_id, product_name, amount) values (4, 'Системный блок', 39000);
insert into orders (customer_id, product_name, amount) values (4, 'Монитор', 11000);
insert into orders (customer_id, product_name, amount) values (1, 'Ноутбук', 47000);
insert into orders (customer_id, product_name, amount) values (1, 'Принтер', 21000);
insert into orders (customer_id, product_name, amount) values (1, 'Смартфон', 19000);
